@startuml
Class System
Abstract class Robot
class Sweeper
class Vacuum
class Mopper
class Room
class Logger
System *-- Robot
Robot <|-- Sweeper
Robot <|-- Vacuum
Robot <|-- Mopper
System *-- Room
System *-- Logger
Room --> Robot

@enduml