@startuml
Class System{
    -robotList : List
    -roomList : List
    +queryRobotStatus(listRobots)
    +queryRoomStatus(listRooms)
    +clean(room, listRobots)
    +repair(robot)
    +recharge(robot)
}
Abstract class Robot{
    -id : String
    -type : enum
    -size : enum
    -cleanTime : int
    -breakOdds : float
    -maxBattery : int
    -battery : int
    -activityStatus : enum
    -lastUsed : Date
    +getID()
    +getStatus()
    +getType()
    +getBattery()
    +getMaxBattery()
    +setBattery()
    +getCleanTime()
    +getBreakOdds()
    +setActivityStatus()
    +setLastUsed()
    +getLastUsed()
}
class Sweeper
class Vacuum
class Mopper
class Room{
    -name : String
    -size : enum
    -clean : Boolean
    +isClean()
    +getSize()
    +getName()
}
class Logger{
    -snapshotInterval
    -saveFile
    -save(data)
    -serialize(listData)
}
System *-- Robot
Robot <|-- Sweeper
Robot <|-- Vacuum
Robot <|-- Mopper
System *-- Room
Logger -> System

@enduml