@startuml
User -> cleaningSystem : Clean command (list of robot ids and room)
cleaningSystem -> Room : Request room status
Room -> cleaningSystem : Supply room status
alt Room status is being cleaned 
    cleaningSystem -> User : Error message (cleaning in progress)
else Room status is dirty or clean
    loop For each robot
    cleaningSystem -> Robot : Request robot status\nand cleaning time 
    Robot -> cleaningSystem : Supply robot status\nand cleaning time
    alt Robot is broken or already occupied
        cleaningSystem -> User : Error message (robot occupied or broken)
    else
        cleaningSystem -> cleaningSystem : Add robot cleaning ability to total
    end
    end
    cleaningSystem -> Room : Request room size
    Room -> cleaningSystem : Supply room size
    cleaningSystem -> cleaningSystem : Calculate cleaning time
    loop For each robot
    cleaningSystem -> Robot : Set status to cleaning
    end
    cleaningSystem -> Room : Change clean to false
    cleaningSystem -> cleaningSystem : Launch async thread
    loop while time < cleaning_time
        activate cleaningSystem #LightBlue
        loop For each robot
        cleaningSystem -> cleaningSystem : Check if robot has broken
        alt Robot breaks or runs out of battery
            cleaningSystem -> User : Error message
        else else
            cleaningSystem -> Robot : Deplete Battery Level
            end
        end
        cleaningSystem -> cleaningSystem : Sleep 1 second
    end
    loop For each robot
    cleaningSystem -> Robot : Set status to availible
    end
     cleaningSystem -> Room : Update status to clean and \nset occupied status to false
    deactivate cleaningSystem
end

@enduml