@startuml

User -> Main: Enters command to repair robot
Main -> System: Calls repair and passes the ids of robots to repair
loop For each robot id
    System -> Robot : Call fixRobot and update robot status to ready
end
System -> User: Message [sucessfully fixed robots.] 

@enduml 