@startuml loggerSequence


actor CSVfile
actor cleaningSystem
actor Robot
actor Room

hide footbox
cleaningSystem -> cleaningSystem : collect number of robots\nand rooms and any info\nfor column titles
cleaningSystem -> CSVfile : add column titles

loop every time user returns to main menu
    cleaningSystem -> cleaningSystem : get robot status vector\nfrom queryRobotStatus()
    cleaningSystem -> cleaningSystem : get room status vector\nfrom queryRoomStatus()
    cleaningSystem -> cleaningSystem : get local time 
    cleaningSystem -> CSVfile : add local time to first column
    loop For each robot
        cleaningSystem -> CSVfile : add robot status and battery
        end
    loop For each room
        cleaningSystem -> CSVfile : add room cleanliness and\noccupied status
        end
end

@enduml loggerSequence