@startuml

User -> Main: Selects Recharge command
Main -> System: calls recharge and passes a list of chargeable robot Ids 

loop For each robot id
    System -> Robot: call chargeRobot to update battery level to full
end

System -> User: Message [sucessfully recharged.]

@enduml
