@startuml

User -> System: Enters Recharge command
activate System #YellowGreen
System-> System: Battery swap simulation (through passage of time)
System -> Robot: Update battery level to full
deactivate
System -> User: Message [sucessfully recharged.]

@enduml