@startuml
User -> ProgramMain : supply robot ids
ProgramMain -> cleaningSystem : Request robot status info
loop For each robot
cleaningSystem -> Robot : Request type, activity status, \nand battery level
Robot -> cleaningSystem : Send back type, activity status, \n and time last in use
cleaningSystem -> cleaningSystem : Package/format data
end 
cleaningSystem -> ProgramMain : send data for robot
ProgramMain -> User : Output formatted data 

@enduml