@startuml

User ->  ProgramMain: Select rooms to be queried
ProgramMain -> cleaningSystem : sends list of robot IDs
loop For each room
cleaningSystem -> Room: Requests status
Room -> cleaningSystem: Returns Status [size,\ncleanliness, occupied status]
cleaningSystem -> cleaningSystem : Format Data
end
cleaningSystem -> ProgramMain : Outputs status vector
ProgramMain -> ProgramMain : Formats vector into output\nstring
ProgramMain -> User : Prints information

@enduml